// <auto-generated />
namespace TFD_AndreySchemel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class TFD_Andrey1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TFD_Andrey1));
        
        string IMigrationMetadata.Id
        {
            get { return "201709060008079_TFD_Andrey1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
